### ISSUE TITLE
Design simple representation of blockly code

### ISSUE THREAD

**Issue by effa** [adaptive-learning/flocs-core#10]
Probably in JSON. Write a conversion function from Blockly XML to the simple representation (and possibly back).

**Comment by xpelanek** [comment]
JSON should be fine (would be user friendly for analysis).
What about postfix notation (reverse polish notation)? (I'm not sure whether it can capture all required stuff.) Probably less user friendly, but  more compact than JSON.

**Comment by effa** [comment]
Basic version done (in json, but reasonably brief; transformation from json to a more compact form can be implemented later, if needed).
