### ISSUE TITLE
Create FixedThenRandom recommender

### ISSUE THREAD

**Issue by effa** [adaptive-learning/flocs-core#66]
1) some tasks in fixed order
2) random for unsolved
3) random from all except from the last one

+ tests

**Comment by matej-vanek** [comment]
What does mean "except from the last one"? Is there some "last task"?

**Comment by effa** [comment]
It means the last task the student has just solved. Just not to give the student the same task twice in a row (if she has solved it).

**Comment by matej-vanek** [comment]
Done in e6ef0b3.
