### ISSUE TITLE
Add level and credits to Student, remove last_session_id

### ISSUE THREAD

**Issue by effa** [adaptive-learning/flocs-core#67]
+ there are two credit items: total credits earned and current credits (for current level, "unspent credits)

**Comment by effa** [comment]
Level can be a computed property from credits

**Comment by matej-vanek** [comment]
Current credits can be computed from total credits too (if credits needed for each level are known).

**Comment by matej-vanek** [comment]
Levels and credits done in ce71355. Last_task_session_id not removed - implementation of timestamps in TaskSession needed.
